// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"SuperBizAgent/api/chat"
	"SuperBizAgent/internal/ai/agent/chat_pipeline"
	"SuperBizAgent/internal/conversation"
	"SuperBizAgent/internal/logic/sse"
	"context"
	"errors"
	"time"

	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/schema"
)

type ControllerV1 struct {
	service       *sse.Service
	conversations conversation.ConversationStore
	coordinator   *conversation.Coordinator
	loops         *conversation.TurnLoopRegistry
	limiter       *conversation.RunLimiter
	runtime       *chat_pipeline.Runtime
}

func appendTurn(ctx context.Context, store conversation.ConversationStore, key conversation.SessionKey, idempotencyKey string, userMessage, assistantMessage *schema.Message) error {
	if idempotencyKey == "" {
		return store.Append(ctx, key, userMessage, assistantMessage)
	}
	idempotent, ok := store.(conversation.IdempotentConversationStore)
	if !ok {
		return errors.New("conversation store does not support idempotency keys")
	}
	_, err := idempotent.AppendIdempotent(ctx, key, idempotencyKey, userMessage, assistantMessage)
	return err
}

func NewV1(runtime *chat_pipeline.Runtime) chat.IChatV1 {
	return NewV1WithStore(runtime, nil)
}

// NewV1WithStore allows deployment wiring to select a durable conversation
// store. A nil store retains the development-friendly memory implementation.
func NewV1WithStore(runtime *chat_pipeline.Runtime, store conversation.ConversationStore) chat.IChatV1 {
	if store == nil {
		store = conversation.NewMemoryStore(6)
	}
	return &ControllerV1{
		service:       sse.New(),
		conversations: store,
		coordinator:   conversation.NewCoordinator(),
		loops:         conversation.NewTurnLoopRegistryWithIdle(128, 30*time.Minute),
		limiter:       conversation.NewRunLimiter(100),
		runtime:       runtime,
	}
}

func (c *ControllerV1) turnSession(ctx context.Context, key conversation.SessionKey) (*conversation.TurnLoopSession, error) {
	if c.runtime == nil || c.runtime.ADKAgent == nil {
		return nil, errors.New("chat agent runtime is not initialized")
	}
	return c.loops.GetOrCreate(ctx, key, func(context.Context) (adk.Agent, error) {
		return c.runtime.ADKAgent, nil
	})
}

func (c *ControllerV1) buildTurnInput(ctx context.Context, key conversation.SessionKey, question string) (*adk.AgentInput, error) {
	history, _, err := c.conversations.Load(ctx, key)
	if err != nil {
		return nil, err
	}
	messages := make([]*schema.Message, 0, len(history)+1)
	messages = append(messages, history...)
	messages = append(messages, schema.UserMessage(question))
	return &adk.AgentInput{Messages: messages}, nil
}

func (c *ControllerV1) Close(ctx context.Context) error {
	if c.loops == nil {
		if c.limiter != nil {
			c.limiter.Close()
		}
		return nil
	}
	if c.limiter != nil {
		c.limiter.Close()
	}
	return c.loops.StopAll(ctx)
}
